name: Build and Push assets to 'main' branch - GH Pages
'on':
  push:
    branches:
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - name: Install
        run: npm install -g npm@8 && npm ci
        env:
          CI: ""
      - name: Build
        run: npm run build
        env:
          CI: ""
      
      - name: Push built assets
        run: |
          git config --global user.name "gh-actions-robot"
          git config --global user.email "gh-actions-robot@random-temp-test-robots.inc"
          echo "node_modules/" > .gitignore
          echo ".cache/" >> .gitignore
          git add .
          git commit -m "Built Static Assets"
          git filter-branch --prune-empty --subdirectory-filter public HEAD
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/mars-ars/mars-ars.github.io
          git push --force origin HEAD:main